package config

const (
	WINDOW_WIDTH  = 640
	WINDOW_HEIGHT = 480

	SCREEN_LENGTH = 330

	BOARD_LENGTH = SCREEN_LENGTH - OUTER_MARGIN*2
	OUTER_MARGIN = 5
	GRID_WIDTH   = 1
	CELL_LENGTH  = (SCREEN_LENGTH - OUTER_MARGIN*2) / 8

	CELL_EMPTY = 0
	CELL_BLACK = 1
	CELL_WHITE = 2
)
