package config

const (
	SCREEN_WIDTH  = 330
	SCREEN_HEIGHT = 330

	BORDER_WIDTH = 5
	RECT_WIDTH   = SCREEN_WIDTH - BORDER_WIDTH*2
	RECT_HEIGHT  = SCREEN_HEIGHT - BORDER_WIDTH*2
	GRID_WIDTH   = 1
	RECT_LENGTH  = (SCREEN_WIDTH - BORDER_WIDTH*2) / 8

	CELL_EMPTY = 0
	CELL_BLACK = 1
	CELL_WHITE = 2
)
